export const DEMO_PROFILES = [
  {
    id: "demo-1",
    name: "Ananya Sharma",
    age: 26,
    gender: "Female",
    location: "Bangalore, India",
    profession: "Yoga Instructor",
    bio: "Passionate about mindfulness and connecting with like-minded souls. Love morning meditations and evening stargazing.",
    photos: ["/demo/profile-1.svg"],
    spiritual_community: "Isha",
    sun_sign: "Pisces",
    diet: "Vegetarian",
    tier: "free",
    is_profile_complete: true,
    spiritual_practices: ["Shambhavi Mahamudra", "Hatha Yoga"],
    ai_archetype: "The Seeker",
  },
  {
    id: "demo-2",
    name: "Rohan Patel",
    age: 28,
    gender: "Male",
    location: "Mumbai, India",
    profession: "Software Engineer",
    bio: "Tech by day, meditation by night. Looking for someone who understands the balance between modern life and ancient wisdom.",
    photos: ["/demo/profile-2.svg"],
    spiritual_community: "Isha",
    sun_sign: "Leo",
    diet: "Vegetarian",
    tier: "free",
    is_profile_complete: true,
    spiritual_practices: ["Inner Engineering", "Yogasanas"],
    ai_archetype: "The Modern Mystic",
  },
  {
    id: "demo-3",
    name: "Priya Nair",
    age: 24,
    gender: "Female",
    location: "Chennai, India",
    profession: "Classical Dancer",
    bio: "Dancing through life with grace and gratitude. Believer in karma and cosmic connections.",
    photos: ["/demo/profile-3.svg"],
    spiritual_community: "Art of Living",
    sun_sign: "Cancer",
    diet: "Vegan",
    tier: "free",
    is_profile_complete: true,
    spiritual_practices: ["Sudarshan Kriya", "Bharatanatyam"],
    ai_archetype: "The Creative Soul",
  },
  {
    id: "demo-4",
    name: "Arjun Mehta",
    age: 30,
    gender: "Male",
    location: "Delhi, India",
    profession: "Ayurveda Practitioner",
    bio: "Healing through ancient wisdom. Looking for a partner who values holistic living and spiritual growth.",
    photos: ["/demo/profile-4.svg"],
    spiritual_community: "Brahma Kumaris",
    sun_sign: "Sagittarius",
    diet: "Sattvic",
    tier: "premium",
    is_profile_complete: true,
    spiritual_practices: ["Rajyoga Meditation", "Pranayama"],
    ai_archetype: "The Healer",
  },
  {
    id: "demo-5",
    name: "Meera Reddy",
    age: 27,
    gender: "Female",
    location: "Hyderabad, India",
    profession: "素食 Chef",
    bio: "Cooking with love and consciousness. Every meal is a prayer. Seeking someone who appreciates mindful living.",
    photos: ["/demo/profile-5.svg"],
    spiritual_community: "ISKCON",
    sun_sign: "Taurus",
    diet: "Vegetarian",
    tier: "free",
    is_profile_complete: true,
    spiritual_practices: ["Krishna Consciousness", "Kirtan"],
    ai_archetype: "The Nurturer",
  },
  {
    id: "demo-6",
    name: "Vikram Singh",
    age: 29,
    gender: "Male",
    location: "Jaipur, India",
    profession: "Astrologer",
    bio: "Reading the stars to guide souls. Believe that every constellation tells a love story waiting to unfold.",
    photos: ["/demo/profile-6.svg"],
    spiritual_community: "TM",
    sun_sign: "Scorpio",
    diet: "Vegetarian",
    tier: "free",
    is_profile_complete: true,
    spiritual_practices: ["Transcendental Meditation", "Jyotish"],
    ai_archetype: "The Mystic",
  },
];
